name: example
description: Example app showcasing my_design_system components.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  my_design_system:
    path: ../ 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

